# Generated by Django 5.0.3 on 2024-07-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=10)),
                ('terminal_id', models.CharField(max_length=8)),
                ('terminal_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('location', models.CharField(choices=[('onsite', 'Onsite'), ('offsite', 'Offsite')], max_length=10)),
            ],
        ),
    ]
