# Generated by Django 5.0.3 on 2024-07-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=10)),
                ('terminal_id', models.CharField(max_length=50)),
                ('terminal_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=10)),
                ('ip', models.GenericIPAddressField()),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ATMTerminal',
        ),
    ]
