# Generated by Django 5.0.3 on 2024-07-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0003_terminal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='status',
            field=models.CharField(default='Operational', max_length=50),
        ),
    ]
